import numbers
import math
print("####################")
print("Input Format: a+bj")
Rez = input("a = ")
Imz = input("b = ")
z = complex(Rez, Imz)
print("####################")
print("Re(z) = " + str(z.real))
print("Im(z) = " + str(z.imag))
print("####################")
print("z = " + str(z))
print("_")
print("z = " + str(z.conjugate()))
print("####################")
print("-z = " + str(-z))
print(" _")
print("-z = " + str(-1*(z.conjugate())))
print("####################")
print("     _         _")
print("|z|=|z|=|-z|=|-z|= " + str(math.sqrt(z.real*z.real+z.imag*z.imag)))
print("####################")
print("Thank you for using complex.py")